source $(brew --prefix)/share/antigen/antigen.zsh
source $(dirname $(readlink ${(%):-%x}))/zshenv


export PATH=~/Projects/go/bin:$PATH
#
# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle autojump
antigen bundle command-not-found
antigen bundle fzf
antigen bundle git
antigen bundle history
antigen bundle pip
antigen bundle pipenv
antigen bundle zsh-history-substring-search.zsh

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle dracula/zsh
antigen bundle Tarrasch/zsh-bd
antigen bundle docker/cli contrib/completion/zsh
antigen bundle docker/compose contrib/completion/zsh

# Load the theme.
antigen theme dracula/zsh dracula

antigen apply

command -v vg >/dev/null 2>&1 && eval "$(vg eval --shell zsh)"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
